#! /bin/sh

startFlashFocus &
feh --bg-scale $HOME/Pictures/forestpath.jpg &
start-picom &
launch_polybar &
sleep 0.5s &&
initKeyboard &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          8
bspc config top_padding		22
bspc config bottom_padding	-4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a VSCodium desktop='^3'

#initSystem &
