#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

if [[ $class = firefox ]]
then
	title=$(xtitle "$wid")
	if [[ $title = 'Enter name of file to save to…' ]]
	then
		xdo resize -w -500 -h -500
	fi
fi
