#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

# if [ "$class" = 'firefox' ];
# then
# title=$(xtitle "$wid")
# if [[ $title = "Enter name of file to save to…" ]]
# then
# echo "floating = on"
# xdotool windowmove $wid 0 0
# bspc node 35651588 -t floating
# bspc node -t floating
# idwm=$(bspc query -N -n $consequences)
# bspc node $idwm -t floating
bspc node  -f `xdotool search --name "Enter name of file to save to…"`
idfs=$(xdotool getwindowfocus)
		# focuswindow=$(xdotool getwindowfocus)
		# n=$(bspc query -N -n newest)
		# bspc node $idfs -t floating
		xdo resize -t $idfs -w -500 -h -500
	
		# xdo resize -w -500 -h -500
# fi
# fi
