#!/bin/bash

focuswindow=$(xdotool getwindowfocus)
geometry=$(xdotool getwindowgeometry $focuswindow | sed -n '/Geometry/{s/.* Geometry: //p}')
isfloating=$(bspc query -N -n $focuswindow.floating)

if [[ -z $isfloating ]]
then
	if [[ $geometry = 698x734 || $geometry = 710x768 ]]
	then
		bspc node -s east
	fi
	bspc node -t floating
else
	bspc node -t tiled
fi
