#!/bin/bash

focuswindow=$(xdotool getwindowfocus)
geometry=$(xdotool getwindowgeometry $focuswindow | sed -n '/Geometry/{s/.* Geometry: //p}')
workspace=$(xdotool get_desktop)
isfloating=$(i3get -a -r f)

if [[ $geometry = '671x734' || $geometry = '683x768' ]]
then
  i3-msg mark swap
  i3-msg focus right
  i3-msg swap container with mark swap
  i3-msg unmark swap
  i3-msg focus right
  i3-msg floating toggle
elif [ $isfloating = 'user_on' ]
then
  i3-msg floating toggle
  focuswindow=$(xdotool getwindowfocus)
  geometry=$(xdotool getwindowgeometry $focuswindow | sed -n '/Geometry/{s/.* Geometry: //p}')
  if [[ $geometry = '1350x244' || $geometry = *"1366"* ]]
  then
    i3-msg move left
    echo left
  elif [[ $geometry = '330x734' || $geometry = '342x768' ]]
  then
    i3-msg move down
    echo down
  elif [ $geometry = '671x180' ]
  then
    i3-msg move right
    echo right
  elif [ $geometry = '1350x372' ]
  then
    i3-msg move right
    echo right
  elif [ $geometry = '444x734' ]
  then
    i3-msg move left
    echo left
  fi
else
  i3-msg floating toggle
fi
