#!/bin/sh

gaps=$(bspc config window_gap)
if [[ $gaps = 0 ]]
then
	bspc config window_gap 8
	bspc config top_padding 30
	bspc config bottom_padding -4
	start-picom
else
	bspc config window_gap 0
	bspc config top_padding 30
	bspc config bottom_padding 0
	killall picom
fi
