#!/bin/sh

gaps=$(bspc config window_gap)
if [[ $gaps = 0 ]]
then
	bspc config window_gap 8
	bspc config top_padding 22
	bspc config bottom_padding -4
	bspc config border_width 0
	start-picom
else
	bspc config window_gap 0
	bspc config top_padding 0
	bspc config bottom_padding 0
	bspc config focused_border_color "#87c095"
	bspc config normal_border_color "#323d43"
	bspc config border_width 1
	killall picom
fi
