#!/bin/sh
focusedDesktop=$(bspc query -D -d .focused)
focusWindow=$(bspc query -N -n .focused -d "$focusedDesktop")
Hidden=$(bspc query -N -n .hidden -d $focusedDesktop)
if [[ -z $Hidden ]]
then
  Nodes=$(bspc query -N -n .tiled -d $focusedDesktop)
  for node in $Nodes; do
    if [[ $node -ne $focusWindow ]]
    then
      bspc node $node -g hidden=on
    fi
  done
else
  for node in $Hidden; do
    bspc node $node -g hidden=off
  done
fi
