#!/bin/bash

currentEngine=$(ibus engine)

if [[ $currentEngine = *'Bamboo'* ]]
then
	ibus engine xkb:jp::jpn
	initKeyboard
	polybar-msg hook checkengine 1
else
	ibus engine BambooUs
	initKeyboard
	polybar-msg hook checkengine 2
fi

