#!/bin/bash

currentEngine=$(ibus engine)

if [[ $currentEngine = *'Bamboo'* ]]
then
	ibus engine xkb:jp:kana86:jpn
	initKeyboard
	polybar-msg hook checkengine 1
else
	ibus engine Bamboo
	initKeyboard
	polybar-msg hook checkengine 2
fi

