#!/bin/sh

#setxkbmap jp &&
# xmodmap -e "keycode 62 = Return NoSymbol Return"
# return 36
#xmodmap -e "keycode 102 = Super_L NoSymbol Super_L" 
#xmodmap -e "keycode 101 = Escape NoSymbol Escape"
#xmodmap -e "keycode 90 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 108 = Escape"

xset r rate 300 50
