#!/bin/sh

master=$(bspc query -N -n biggest.local)
focused=$(bspc query -N -n .focused)

if [[ $master == $focused ]]; then
  bspc node $(bspc query -N -n last.local) -s $master
  bspc node -f $(bspc query -N -n biggest.local)
  bspc node $master -c
else
  bspc node -c
fi
