#!/bin/bash

isfloating=$(i3get -a -r f)
focuswindow=$(xdotool getwindowfocus)
geometry=$(xdotool getwindowgeometry $focuswindow | sed -n '/Geometry/{s/.* Geometry: //p}')
position=$(xdotool getwindowgeometry $focuswindow | sed -n '/Position/{s/.* Position: //p}')
if [ "$isfloating" != "user_on" ]
then
  if [ $geometry = '671x734' ] && [ "$position" = "8,26 (screen: 0)" ]
  then
    i3-msg mark swap
    i3-msg focus right
    i3-msg swap container with mark swap
    i3-msg unmark swap
    i3-msg focus right
    i3-msg move container to workspace number $1
  else
    i3-msg move container to workspace number $1
  fi
else
  i3-msg move container to workspace number $1
fi
