#!/bin/bash
xmodmap -e "keycode 62 = Return NoSymbol Return"
xmodmap -e "keycode 102 = Super_L NoSymbol Super_L"
xmodmap -e "keycode 101 = Escape NoSymbol Escape"
xmodmap -e "keycode 90 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 87 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 83 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 79 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 80 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 84 = BackSpace BackSpace BackSpace"
xmodmap -e "keycode 88 = BackSpace BackSpace BackSpace"
xset r rate 300 50
