#!/bin/sh

bspc subscribe node_add | while read line
do
  idwm=$(echo "$line" | awk '{print $5}')
  wdname=$(xdotool getwindowname $idwm)
  # echo $wdname
  if [ "$wdname" = "Enter name of file to save to…" ]
  then
    # bspc node $idwm -t floating
    xdo resize -t $idwm -w -500 -h -500
  fi
done
