#! /bin/sh

bspc rule -r "*"

startFlashFocus &
feh --bg-fill $HOME/Pictures/undersea_of_nord.png &
start-picom &
sleep 0.5s &&
#killall ibus-daemon &&
#ibus-daemon -drx &&
#initKeyboard &
wmname LG3D &
cleanfullscreen &
alacritty &
sleep 0.5s &&
launch_polybar &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width    0
bspc config window_gap      8
bspc config top_padding		22
bspc config bottom_padding	-4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color #87c095
bspc config normal_border_color #323d43
for p in {single,borderless}_monocle; do bspc config "$p" true; done

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a VSCodium desktop='^3'
bspc rule -a firefox desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Sxiv state=floating
bspc rule -a jetbrains-rider  desktop='^4'
bspc rule -a jetbrains-datagrip desktop='=^6'
bspc rule -a kitty
bspc rule -a Brave-browser desktop='^2'
bspc rule -a figma-linux desktop='^3'
bspc rule -a KeePassXC desktop='^5'
bspc rule -a jetbrains-clion desktop='^4'
bspc rule -a Zathura desktop='^7'
bspc rule -a xdman-Main state=floating
bspc rule -a mpv desktop='^8' state=floating
bspc rule -a Wps desktop="5"
