#! /bin/sh

bspc rule -r "*"

startFlashFocus &
wallpaper 'darkplus' &
start-picom &
wmname LG3D &
#bspswallow &
launch_polybar &
# initKeyboard &
alacritty &
desknamer &
sxhkd &
~/.config/bspwm/masterlayout.sh &
bspc config external_rules_command  ~/.config/bspwm/external_rules.sh

bspc config border_width    1
bspc config window_gap      8
bspc config top_padding		22
bspc config bottom_padding	-4
bspc config removal_adjustment      false

bspc config split_ratio          0.50
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color "#3e3e3e"
bspc config normal_border_color "#1e1e1e"
for p in {single,borderless}_monocle; do bspc config "$p" true; done

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a VSCodium desktop='^3'
bspc rule -a firefox desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Sxiv state=floating
bspc rule -a jetbrains-rider  desktop='^4'
bspc rule -a jetbrains-datagrip desktop='=^4'
bspc rule -a jetbrains-webstorm desktop='=^4'
bspc rule -a kitty
bspc rule -a Brave-browser desktop='^2'
bspc rule -a figma-linux desktop='^3'
bspc rule -a KeePassXC desktop='^5'
bspc rule -a jetbrains-clion desktop='^4'
bspc rule -a Zathura desktop='^7'
bspc rule -a xdman-Main state=floating
bspc rule -a mpv desktop='^8'
bspc rule -a Wps desktop="5"
bspc rule -a firefox:firefox:"File Upload" rectangle=1000x700+0+0
bspc rule -a Code:code:"Open Folder" rectangle=1000x700+0+0
bspc rule -a Electron9:electron9:"Open" rectangle=1000x700+0+0
bspc rule -a jetbrains-idea:jetbrains-idea:"New Project" rectangle=1000x700+0+0
bspc rule -a Microsoft-edge:microsoft-edge desktop='^2'
bspc rule -a Microsoft-edge:microsoft-edge rectangle=1000x700+0+0
bspc rule -a Figma-linux:figma-linux rectangle=1000x700+0+0
bspc rule -a Mongodb-compass:mongodb-compass rectangle=1000x700+0+0
bspc rule -a mpv rectangle=1300x700+0+0
bspc rule -a "MEGAsync" state=floating follow=on
bspc rule -a alacritty rectangle=644x725+0+0
bspc rule -a slack desktop='3'
bspc rule -a insomnia desktop='3'
bspc rule -a Fig state=floating layer=above border=off
bspc rule -a Alacritty:popup state=floating
bspc rule -a "Genymotion Player":player state=floating
bspc rule -a ksnip:ksnip state=floating rectangle=831x684 center=true
bspc rule -a Farge state=floating
