#!/bin/sh

# @Basics
# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# terminal emulator
super + Return
	alacritty msg create-window

# close and kill
super + w
  killwindow

# Use pactl to control volume
XF86AudioRaiseVolume
	pactl set-sink-volume @DEFAULT_SINK@ +1%

XF86AudioLowerVolume
	pactl set-sink-volume @DEFAULT_SINK@ -1%

XF86AudioMute
	pactl set-sink-mute @DEFAULT_SINK@ toggle

# Use brightnessctl to adjust screen brightness
XF86MonBrightnessDown
	xbacklight -dec 5%

XF86MonBrightnessUp
	xbacklight -inc 5%

# Desktop screenshot
Print
	flameshot gui

# Change ibus engine
alt + shift + Return
	ibus-engine-switcher

alt + @space
	dmenu_run -l 10

super + alt + Return
  switch-color-scheme

# @Navgiations
# Change focus
super + {j,k}
    bspwm-window-cycle --focus {'next', 'prev'}

super + {h,l}
  bspc desktop -f {prev.occupied,next.occupied}

# Move window
super + shift + {j,k}
    bspwm-window-cycle --move {'next','prev'}

# Move floating window to far most direction
alt + ctrl + shift {h,l}
  move-floating {'far-left', 'far-right'}

super + ctrl + {h,j,k,l}
	bspc node -z {left -5 0,bottom 0 5,top 0 -5,right 5 0}

super + ctrl + shift + {h,j,k,l}
	bspc node -z {right -5 0,top 0 5,bottom 0 -5,left 5 0}

# Focus master
super + space
  toggle-focus-master

# Promote to master
super + shift + space
  toggle-swap-master

# Change desktop
super + {1-9,0}
    bspc desktop --focus ^{1-9,10}

# Move to desktop
super + shift + {1-9,0}
    bspc node --to-desktop ^{1-9,10}

# focus the last node/desktop
super + {Tab}
	bspc desktop -f last

# focus last floating window
super + s
  toggle-focus-floating

# focus next occupied desktop
super + grave
  bspc desktop -f next.occupied

# @Resize
# Resize
super + ctrl {h,l}
  bspwm_node_resize {west,east}

# super + ctrl {j,k}
#   bspc node -z {bottom 0 5} 

# @Layout
# Enter focus mode
super + shift + f
	focus

# Bspwm floating is suck too
super + shift + s
	floater

super + f
  fullscreen

ctrl + b
  balance
