lastupdatecheck: 0
recentrepos:
- /home/nick/.local/share/lunarvim/lvim
- /home/nick/Downloads/Git_Clone/learning-lua-plugin.nvim
- /home/nick/.config/nvim
- /home/nick/Downloads/Git_Clone/dotfile-2021
- /home/nick/Documents/react-hooks
- /home/nick/Documents/typescript-academind
startuppopupversion: 5
