env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: alacritty

window:
  padding:
    x: 30
    y: 20

  dynamic_padding: true

  title: Alacritty

  dynamic_title: true

  # Window class (Linux/BSD only):
  # class:
  #   # Application instance name
  #   instance: Alacritty
  #   # General application class
  #   general: Alacritty

  gtk_theme_variant: None
  # opacity: 0.95

decorations: full

draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: JetBrains Mono Nerd Font # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: JetBrains Mono Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: JetBrains Mono Nerd Font
    # Style can be specified to pick a specific face.
    style: Italic

  bold_italic: 
    family: JetBrains Mono Nerd Font
    style: Bold Italic
  # The size to use.
  size: 9
  offset:
    x: 0
    y: 0

# The definition of color schemes.
schemes:
# github Alacritty Colors
  github_dark_default: &github_dark_default
    primary:
      background: '#0d1117'
      foreground: '#b3b1ad'
    normal:
      black:   '#484f58'
      red:     '#ff7b72'
      green:   '#3fb950'
      yellow:  '#d29922'
      blue:    '#58a6ff'
      magenta: '#bc8cff'
      cyan:    '#39c5cf'
      white:   '#b1bac4'
    bright:
      black:   '#6e7681'
      red:     '#ffa198'
      green:   '#56d364'
      yellow:  '#e3b341'
      blue:    '#79c0ff'
      magenta: '#d2a8ff'
      cyan:    '#56d4dd'
      white:   '#f0f6fc'

    indexed_colors:
      - { index: 16, color: '#d18616' }
      - { index: 17, color: '#ffa198' }
  github_dark: &github_dark
    primary:
      background: "#24292e"
      foreground: "#d1d5da"
    normal:
      black: "#24292e"
      red: "#f14c4c"
      green: "#23d18b"
      yellow: "#e2e210"
      blue: "#3b8eea"
      magenta: "#bc3fbc"
      cyan: "#29b7da"
      white: "#d1d5da"

    # Bright colors
    bright:
      black: "#666666"
      red: "#f14c4c"
      green: "#23d18b"
      yellow: "#f5f543"
      blue: "#3b8eea"
      magenta: "#d670d6"
      cyan: "#29b7da"
      white: "#d1d5da"

    indexed_colors:
      - { index: 16, color: "#d18616" }
      - { index: 17, color: "#f14c4c" }
  github_dimmed: &github_dimmed
    primary:
      background: "#22272e"
      foreground: "#d1d5da"
    normal:
      black: "#22272e"
      red: "#ff938a"
      green: "#6bc46d"
      yellow: "#c69026"
      blue: "#6cb6ff"
      magenta: "#b083f0"
      cyan: "#56d4dd"
      white: "#768390"
    bright:
      black: "#636e7b"
      red: "#ff938a"
      green: "#6bc46d"
      yellow: "#daaa3f"
      blue: "#6cb6ff"
      magenta: "#dcbdfb"
      cyan: "#56d4dd"
      white: "#768390"

    indexed_colors:
      - { index: 16, color: "#d18616" }
      - { index: 17, color: "#ff938a" }
  gruvbox_material_hard_dark: &gruvbox_material_hard_dark
    primary:
      background: "#1d2021"
      foreground: "#d4be98"
    normal:
      black: "#32302f"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"
    bright:
      black: "#32302f"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"
  gruvbox_material_medium_dark: &gruvbox_material_medium_dark
    primary:
      background: "#282828"
      foreground: "#d4be98"
    normal:
      black: "#3c3836"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"
    bright:
      black: "#3c3836"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"
  gruvbox_material_soft_dark: &gruvbox_material_soft_dark
    primary:
      background: "#32302f"
      foreground: "#d4be98"
    normal:
      black: "#45403d"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"
    bright:
      black: "#45403d"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"
  gruvbox_material_hard_light: &gruvbox_material_hard_light
    primary:
      background: "#f9f5d7"
      foreground: "#654735"
    normal:
      black: "#654735"
      red: "#c14a4a"
      green: "#6c782e"
      yellow: "#b47109"
      blue: "#45707a"
      magenta: "#945e80"
      cyan: "#4c7a5d"
      white: "#f2e5bc"
    bright:
      black: "#654735"
      red: "#c14a4a"
      green: "#6c782e"
      yellow: "#b47109"
      blue: "#45707a"
      magenta: "#945e80"
      cyan: "#4c7a5d"
      white: "#f2e5bc"
  gruvbox_material_medium_light: &gruvbox_material_medium_light
    primary:
      background: "#fbf1c7"
      foreground: "#654735"
    normal:
      black: "#654735"
      red: "#c14a4a"
      green: "#6c782e"
      yellow: "#b47109"
      blue: "#45707a"
      magenta: "#945e80"
      cyan: "#4c7a5d"
      white: "#eee0b7"
    bright:
      black: "#654735"
      red: "#c14a4a"
      green: "#6c782e"
      yellow: "#b47109"
      blue: "#45707a"
      magenta: "#945e80"
      cyan: "#4c7a5d"
      white: "#eee0b7"
  gruvbox_material_soft_light: &gruvbox_material_soft_light
    primary:
      background: "#f2e5bc"
      foreground: "#654735"
    normal:
      black: "#654735"
      red: "#c14a4a"
      green: "#6c782e"
      yellow: "#b47109"
      blue: "#45707a"
      magenta: "#945e80"
      cyan: "#4c7a5d"
      white: "#e6d5ae"
    bright:
      black: "#654735"
      red: "#c14a4a"
      green: "#6c782e"
      yellow: "#b47109"
      blue: "#45707a"
      magenta: "#945e80"
      cyan: "#4c7a5d"
      white: "#e6d5ae"
    window_11: &window_11
      primary:
        background: "#DBE5EE"
        foreground: "#161718"
      normal:
        black: "#161718"
        red: "#D41F33"
        green: "#21916C"
        yellow: "#D2B256"
        blue: "#0C5F97"
        magenta: "#703CB7"
        cyan: "#008C99"
        white: "#FBFBFB"
    one_dark: &one_dark
      primary:
        background: '#1e2127'
        foreground: '#abb2bf'
      normal:
          black:   '#1e2127'
          red:     '#e06c75'
          green:   '#98c379'
          yellow:  '#d19a66'
          blue:    '#61afef'
          magenta: '#c678dd'
          cyan:    '#56b6c2'
          white:   '#828791'
      bright:
        black:   '#5c6370'
        red:     '#e06c75'
        green:   '#98c379'
        yellow:  '#d19a66'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#e6efff'

# Apply the color scheme.
colors: *github_dark_default
